#!/usr/bin/env bash
#
# setup_nvim_v7.sh
#
# Description: Installs vim-plug (if necessary), generates a Neovim
# configuration at ~/.config/nvim/init.vim using a robust plugin suite,
# Gruvbox theme options, and various productivity enhancements.
#
# Usage: ./setup_nvim_v7.sh [-b | --backup] [-t THEME]
#
# Options:
#   -b, --backup      Backup existing init.vim and vim-plug before reinstalling
#   -t, --theme THEME Specify colorscheme (default: gruvbox)
#   -h, --help        Display this help and exit

set -euo pipefail

# -------------------------
# Default Configuration
# -------------------------
NVIM_CONF_DIR="$HOME/.config/nvim"
NVIM_CONF_FILE="$NVIM_CONF_DIR/init.vim"
PLUG_VIM="$HOME/.local/share/nvim/site/autoload/plug.vim"
PLUG_VIM_URL="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
BACKUP=false
THEME="gruvbox"

# -------------------------
# Help / Usage Function
# -------------------------
usage() {
  cat << EOF
Usage: $0 [options]

Options:
  -b, --backup      Backup existing config and vim-plug before reinstalling
  -t, --theme THEME Choose colorscheme (default: gruvbox)
  -h, --help        Display this help and exit
EOF
  exit 0
}

# -------------------------
# Parse Command-Line Arguments
# -------------------------
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -b|--backup) BACKUP=true; shift;;
    -t|--theme) THEME="$2"; shift 2;;
    -h|--help) usage;;
    *) echo "Unknown option: $1"; usage;;
  esac
done

# -------------------------
# Function: install_vim_plug
# -------------------------
install_vim_plug() {
  if [ -f "$PLUG_VIM" ]; then
    echo "→ vim-plug already detected at $PLUG_VIM"
    if [ "$BACKUP" = true ]; then
      echo "  Backing up existing plug.vim to plug.vim.bak"
      mv "$PLUG_VIM" "${PLUG_VIM}.bak"
    fi
    echo "  Reinstalling vim-plug..."
    curl -fLo "$PLUG_VIM" --create-dirs "$PLUG_VIM_URL"
  else
    echo "→ Installing vim-plug..."
    curl -fLo "$PLUG_VIM" --create-dirs "$PLUG_VIM_URL"
  fi
}

# -----------------------------
# Function: create_nvim_config
# -----------------------------
create_nvim_config() {
  echo "→ Generating Neovim configuration at $NVIM_CONF_FILE"
  mkdir -p "$NVIM_CONF_DIR"
  cat <<- INITCONF > "$NVIM_CONF_FILE"
"==============================================================================
" init.vim — generated by setup_nvim_v7.sh
"==============================================================================

" ------------------------
" Editor Options
" ------------------------
set numberwidth=5           " Fixed gutter width to prevent shifting (covers up to 99999 lines)
set signcolumn=yes          " Always show sign column
set number                  " Show absolute line numbers
set relativenumber          " Show relative line numbers
set cursorline              " Highlight current line
set clipboard=unnamedplus   " Use system clipboard
set mouse=a                 " Enable mouse support
set hidden                  " Enable background buffers

INITCONF
}

# -----------------------------
# Main Execution
# -----------------------------
install_vim_plug
create_nvim_config

echo "→ Installing plugins via Neovim (this may take a few minutes...)"
nvim +PlugInstall +qall

echo "✅ Neovim setup complete!"

