#!/usr/bin/env bash
#
# setup_nvim.sh
#
# This script installs vim-plug (if necessary), generates a comprehensive
# Neovim configuration at ~/.config/nvim/init.vim, and then runs PlugInstall.
#
# It also includes Lua snippets to configure certain plugins after installation.
#

# -------------------------
# Configuration Variables
# -------------------------
NVIM_CONF_DIR="$HOME/.config/nvim"
NVIM_CONF_FILE="$NVIM_CONF_DIR/init.vim"
PLUG_VIM="$HOME/.local/share/nvim/site/autoload/plug.vim"
PLUG_VIM_DIR="$(dirname "$PLUG_VIM")"
PLUG_VIM_URL="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# -------------------------
# Function: install_vim_plug
# -------------------------
install_vim_plug() {
    if [ -f "$PLUG_VIM" ]; then
        echo "→ vim-plug already installed at $PLUG_VIM."
        read -r -p "  Backup and reinstall? (y/n): " ans
        if [ "$ans" = "y" ]; then
            mv "$PLUG_VIM" "$PLUG_VIM_DIR/plug_backup.vim"
            echo "  Backed up to plug_backup.vim; reinstalling..."
            curl -fLo "$PLUG_VIM" --create-dirs "$PLUG_VIM_URL"
        else
            echo "  Skipping vim-plug installation."
        fi
    else
        echo "→ Installing vim-plug..."
        curl -fLo "$PLUG_VIM" --create-dirs "$PLUG_VIM_URL"
    fi
}

# -----------------------------
# Function: create_nvim_config
# -----------------------------
create_nvim_config() {
    echo "→ Generating Neovim configuration at $NVIM_CONF_FILE..."
    mkdir -p "$NVIM_CONF_DIR"
    cat << 'EOF' > "$NVIM_CONF_FILE"
"==============================================================================
" init.vim — generated by setup_nvim.sh
"==============================================================================

" Begin plugin section
call plug#begin('~/.vim/plugged')

  " ─────────── Core Utilities ───────────
  Plug 'sheerun/vim-polyglot'          " Universal syntax highlighting
  Plug 'dense-analysis/ale'            " Asynchronous linting

  " ─────────── Development Languages ───────────
  Plug 'davidhalter/jedi-vim'          " Python autocompletion & navigation
  Plug 'arzg/vim-sh'                   " Bash scripting support
  Plug 'jalvesaq/Nvim-R'               " R language integration
  Plug 'pangloss/vim-javascript'       " JavaScript syntax
  Plug 'leafgarland/typescript-vim'    " TypeScript syntax
  Plug 'peitalin/vim-jsx-typescript'   " JSX + TypeScript

  " ─────────── UI & Theming ───────────
  Plug 'morhetz/gruvbox'
  Plug 'joshdick/onedark.vim'
  Plug 'arcticicestudio/nord-vim'
  Plug 'ayu-theme/ayu-vim'
  Plug 'dracula/vim'
  Plug 'NLKNguyen/papercolor-theme'

  " ─────────── File & Buffer Management ───────────
  Plug 'preservim/nerdtree'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'akinsho/bufferline.nvim', {'tag': 'v2.*'}

  " ─────────── Git Integration ───────────
  Plug 'tpope/vim-fugitive'
  Plug 'lewis6991/gitsigns.nvim'
  Plug 'sindrets/diffview.nvim'
  Plug 'akinsho/git-conflict.nvim'

  " ─────────── Completion & Snippets ───────────
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'hrsh7th/nvim-cmp'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/cmp-nvim-lua'
  Plug 'saadparwaiz1/cmp_luasnip'
  Plug 'L3MON4D3/LuaSnip'
  Plug 'rafamadriz/friendly-snippets'

  " ─────────── Treesitter & Syntax ───────────
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  Plug 'nvim-treesitter/playground'
  Plug 'windwp/nvim-ts-autotag'

  " ─────────── LSP & Diagnostics ───────────
  Plug 'neovim/nvim-lspconfig'
  Plug 'j-hui/fidget.nvim'
  Plug 'folke/trouble.nvim'

  " ─────────── Commenting & Pairing ───────────
  Plug 'tpope/vim-commentary'
  Plug 'numToStr/Comment.nvim'
  Plug 'machakann/vim-sandwich'
  Plug 'Yggdroot/indentLine'
  Plug 'jiangmiao/auto-pairs'
  Plug 'windwp/nvim-autopairs'

  " ─────────── Status Line & Key Help ───────────
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'nvim-lualine/lualine.nvim'
  Plug 'folke/which-key.nvim'

  " ─────────── Terminal & Misc ───────────
  Plug 'akinsho/toggleterm.nvim'
  Plug 'preservim/nerdtree'
  Plug 'tpope/vim-surround'

call plug#end()
" End plugin section

" ───────────────────────────────────────────────────────────────────────────────────
" General Settings
"────────────────────────────────────────────────────────────────────────────────────
set number                      " Show line numbers
set clipboard+=unnamedplus      " Use system clipboard
colorscheme gruvbox             " Default colorscheme

" Indentation for shell scripts
autocmd FileType sh setlocal shiftwidth=2 tabstop=2

" Keybindings ──────────────────────────────────────────────────────────────────────
nnoremap <C-s> :w<CR>            " Save file
nnoremap <C-h> :bprev<CR>        " Previous buffer
nnoremap <C-l> :bnext<CR>        " Next buffer
nnoremap <C-j> <C-w>j            " Window down
nnoremap <C-k> <C-w>k            " Window up
nnoremap <C-h> <C-w>h            " Window left
nnoremap <C-l> <C-w>l            " Window right
nnoremap <C-p> :Files<CR>        " FZF file search
nnoremap <C-/> :Commentary<CR>    " Toggle comment
nnoremap <C-n> :NERDTreeToggle<CR> " Toggle NERDTree

" Enable ALE linters
let g:ale_linters = {
\   'python': ['flake8'],
\   'sh':     ['shellcheck'],
\   'javascript': ['eslint'],
\   'typescript': ['tslint'],
\}

" CoC global extensions
let g:coc_global_extensions = [
\ 'coc-pyright',
\ 'coc-tsserver',
\ 'coc-json',
\ 'coc-html',
\ 'coc-css'
\]

" Which-key setup
lua << EOF
require("which-key").setup {}
EOF

"==============================================================================
" Lua-based plugin configuration
" It is recommended to place these in ~/.config/nvim/after/plugin/*.lua
"==============================================================================

lua << EOF
-- Speed up startup by caching Lua modules
require('impatient')

-- Treesitter auto tag and playground
require('nvim-treesitter.configs').setup {
  auto_install = true,
  highlight = { enable = true },
  playground = { enable = true },
  autotag = { enable = true },
}

-- LSP progress widget
require('fidget').setup{}

-- Diagnostics list
vim.api.nvim_set_keymap("n", "<leader>xx", "<cmd>TroubleToggle<cr>",
  { silent = true, noremap = true })

-- Terminal toggling
require("toggleterm").setup{
  size = 20,
  open_mapping = [[<c-\>]],
  shade_terminals = true,
}

-- Comment.nvim
require('Comment').setup{}

-- Autopairs
require('nvim-autopairs').setup{}

-- Lualine statusline
require('lualine').setup{}
EOF

EOF
}

# -----------------------------
# Main Script Execution
# -----------------------------
install_vim_plug
create_nvim_config

echo "→ Installing plugins via Neovim..."
nvim +PlugInstall +qall

echo "✅ Neovim setup complete!"
